** Knower Vs Learner:
* Knower:
- Knower makes conclusive statements e.g. That wont work we tried/know it.
- Here is what we should do
- If we do X then Y-Bad thing- will happen

* Learner:
- Asks open questions e.g. How can we make it happen ?
- What do you think we should do ?
- What I want is X and What I dont want is Y.

Repharse your statements: 
- "Here is what we should do" to *What should we do?* <- simple shifting of the world position to make it a question.
- Keep statements open so that others may add their suggestions to help create solution
  'We Cant' to 'How to.. ?'
  'No.' to 'I wish..'
  'But' to 'Yes and..'
  
  *Minds are like parachutes; they only function when open.* and *Follow this at home too and everywhere in fact for a better life*


** Change:
- Change is NOT an event with a start and an end. It is a constant activity.
- Be aware of the changes around you and keep strategizing accordingly.
- Stop resisting change and move with it
- Speed at which change is happening is only increasing and there is no going back in this
- Sense of Loss Vs Sense of Opportunity: 
  A person with Sense of loss will be attached to the things that are no longer relevant tomorrow and are afraid to lose them.
  A person with Sese of opportunity will look for opportunity and how they can make the most from the change
  
  *How once experiences change is once choice.* It depends on once mindset and influencese once behavior and there by results.
- Job Vs Career Vs Calling: See meaning and impact in your day to day contributions
- Don't say "I provide financial reports to management" try saying "I empower the leadership team with key metrics for making important decisions"

  _Refer_ : The parable of the stonemasons: Are we laying bricks Or building Catherdrals ? Always take a bigger picture of your contribution.
  
  _Refer_ : Zorro circle: Things that I can control and things outside my control; Create right focus.
  
