** Managing Energy:
  - Establish a rhythm between energy spend and recovery i.e. work and break. Lack of break which helps recovery is biggest problem.
  - Start the day and even meetings with the big rocks in mind i.e. Things to achieve on the given day Or meeting.
  - Big rock example here refers to a story of professor filling a bottle with big rocks and then smaller once and then even smaller once while asking students if there is any space left, only for the students to find out that still space is left and more smaller and smaller items can be added.
  - Avoid Multitasking; even *mental* multi tasking.
  - The more you try to avoid/stop thinking about something, your mind thinks even more about it. Paradoxical Intent Or Ironic robound is the term describes this phenominon. Just let that thought go, just switch your focus to another (important) objective i.e. be nonjudgementally aware of the thought.
  - Be mindful of your energy level through out the day and take breaks from time to time. `Turn-off` yourself during this break time.
  - Try reframing negative events into positive events/goals i.e. think more of the pros of an action and on how more actions can be taken to stregthen these pros to once benefit.
  - Reward yourself with small treats from time to time; don't wait for big successful event to celebrate
  - Most importantly build `Tiny habits` to improve life daily
  - When switching tasks take note of where you are ending the current task
  
  References:
  https://www.forbes.com/sites/laurashin/2014/01/15/how-to-perform-at-your-peak-every-day-10-tips-for-working-smarter-in-2014/#544abd081bfa
  https://www.psychologytoday.com/us/blog/creativity-without-borders/201405/the-myth-multitasking
  https://hbr.org/2001/01/the-making-of-a-corporate-athlete
  https://gretchenrubin.com/2017/03/healthy-treats-give-yourself/
  https://hbr.org/2008/02/are-you-using-recognition-effe-1.html
  https://www.tinyhabits.com/
  
